{% set name = "xypattern" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xypattern-{{ version }}.tar.gz
  sha256: 84d8077796ab169b8b7c971b0ec7536068021e357585657d1d15511d2973ebb1

build:
  entry_points:
    - stitch_patterns = xypattern.scripts.stitch_patterns:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - poetry-core
    - cython
    - setuptools
    - poetry-dynamic-versioning
    - pip
  run:
    - python
    - numpy
    - scipy 

test:
  imports:
    - xypattern
  commands:
    - pip check
    - stitch_patterns --help
  requires:
    - pip

about:
  summary: Library for handling x-y pattern data, such as are collected with x-ray diffraction or Raman spectroscopy
  license: MIT
  license_file: LICENSE.txt
  home: https://github.com/CPrescher/xypattern
  dev_url: https://github.com/CPrescher/xypattern

extra:
  recipe-maintainers:
    - t20100
    - CPrescher
