{% set name = "xypattern" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xypattern-{{ version }}.tar.gz
  sha256: 1d5742f7c73ab03d278def475657df0733ab91cb0eb94ccf7e735efae0984b44

build:
  entry_points:
    - stitch_patterns = xypattern.scripts.stitch_patterns:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - poetry-core
    - cython
    - setuptools
    - poetry-dynamic-versioning
    - pip
  run:
    - python
    - numpy >=1.24.0,<2.0.0
    - scipy >=1.9.3,<2.0.0

test:
  imports:
    - xypattern
  commands:
    - pip check
    - stitch_patterns --help
  requires:
    - pip

about:
  summary: Library for handling x-y pattern data, such as are collected with x-ray diffraction or Raman spectroscopy
  license: MIT
  license_file: LICENSE.txt
  home: https://github.com/CPrescher/xypattern
  dev_url: https://github.com/CPrescher/xypattern

extra:
  recipe-maintainers:
    - t20100
    - CPrescher
