{% set name = "xypattern" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xypattern-{{ version }}.tar.gz
  sha256: 33d623be7ec0b4b86d1cd9f4cabfdc6f99f2b16e6e3ef28690aaf3d929c93493

build:
  entry_points:
    - stitch_patterns = xypattern.scripts.stitch_patterns:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - poetry-core
    - cython
    - setuptools
    - poetry-dynamic-versioning
    - pip
  run:
    - python
    - numpy >=1.24.0,<2.0.0
    - scipy >=1.9.3,<2.0.0

test:
  imports:
    - xypattern
  commands:
    - pip check
    - stitch_patterns --help
  requires:
    - pip

about:
  summary: Library for handling x-y pattern data, such as are collected with x-ray diffraction or Raman spectroscopy
  license: MIT
  license_file: LICENSE.txt
  home: https://github.com/CPrescher/xypattern
  dev_url: https://github.com/CPrescher/xypattern

extra:
  recipe-maintainers:
    - t20100
    - CPrescher
